services:
  record_odometry:
    image: ghcr.io/comrob/slam-bench:latest
    init: true
    container_name: record_odometry
    user: "1000:1000"  # Run container as host user
    environment:
      - ROS_HOME=/tmp/.ros
      - OUTPUT_FILE_NAME=${OUTPUT_FILE_NAME}
      - OUTPUT_PATH_HOST=${OUTPUT_PATH_HOST}
    volumes:
      - ${OUTPUT_PATH_HOST}:/trajectory_files
    network_mode: "host"
    entrypoint: ["/rosbag_player/entrypoint_record_odometry.sh"]

  play_bag:
    image: ghcr.io/comrob/slam-bench:latest
    init: true
    container_name: play_bag
    user: "1000:1000"  # Run container as host user
    environment:
      - BAGFILES_PATH_HOST=${BAGFILES_PATH_HOST}
      - BAGFILE_NAME=${BAGFILE_NAME:-sensors}
      - ROSBAG_PLAY_RATE=${ROSBAG_PLAY_RATE}
      - TOPICS_FILE=${TOPICS_FILE}
      - ROS_HOME=/tmp/.ros
    volumes:
      - ${BAGFILES_PATH_HOST}:/rosbag_files
    network_mode: "host"
  
  evaluate_trajectory:
    init: true
    image: ghcr.io/comrob/slam-bench:latest
    container_name: evaluate_trajectory
    user: "1000:1000"  # Run container as host user
    environment:
      - TEST_MODE=${TEST_MODE}
    volumes:
      - ${REFERENCE_TRAJECTORY_FILE_HOST:-/reference_trajectory.txt}:/reference_trajectory.txt
      - ${ESTIMATED_TRAJECTORY_FILE_HOST:-/estimated_trajectory.txt}:/estimated_trajectory.txt
      - ${OUTPUT_PATH_HOST:-/evaluation_output}:/evaluation_output
    entrypoint: ["/rosbag_player/entrypoint_evaluate.sh"]
  
  run_slam_nvidia:
    image: ${SLAM_IMAGE:-$CRL_SLAM_IMAGE}
    container_name: run_slam_nvidia
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  
  run_slam:
    image: ${SLAM_IMAGE:-$CRL_SLAM_IMAGE}
    container_name: run_slam
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${SLAM_CONFIG_OVERRIDE_FILE:-/dev/null}:/config/overrides.yaml
    environment:
      - DISPLAY=${DISPLAY}
  
